apiVersion: v1
kind: Service
metadata:
  name: {{ include "charge-spot-quest.fullname" . }}
  labels:
    {{- include "charge-spot-quest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "charge-spot-quest.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
